

export const migrationTypes = [
    
    'string',
    'text',
    'longText',
    'boolean',
    'integer',
    'date',
    'dateTime',
    'dateTimeTz',
    'float',
    'decimal',
    'double',
    'enum',
    'json',
    'foreignId',
    'foreignIdFor',
    'foreignUuid',
    'morphs',
    'bigInteger',
    'bigIncrements',
    'binary',
    'char',
    'year',
    'geometryCollection',
    'geometry',
    'id',
    'increments',
    'ipAddress',
    'jsonb',
    'lineString',
    'macAddress',
    'mediumIncrements',
    'mediumInteger',
    'mediumText',
    'multiLineString',
    'multiPoint',
    'multiPolygon',
    'nullableMorphs',
    'nullableTimestamps',
    'nullableUuidMorphs',
    'point',
    'polygon',
    'rememberToken',
    'set',
    'smallIncrements',
    'smallInteger',
    'softDeletesTz',
    'softDeletes',
    'timeTz',
    'time',
    'timestampTz',
    'timestamp',
    'timestampsTz',
    'timestamps',
    'tinyIncrements',
    'tinyInteger',
    'tinyText',
    'unsignedBigInteger',
    'unsignedDecimal',
    'unsignedInteger',
    'unsignedMediumInteger',
    'unsignedSmallInteger',
    'unsignedTinyInteger',
    'uuidMorphs',
    'uuid',
]

export const htmlTypes = [
    'text',
    'number',
    'email',
    'select',
    'password',
    'tel',
    'datepicker',
    'switch',
    'search',
    'url',
]

export const fieldDefault = {
    name: '',
    type: 'string',
    htmltype: 'text',
    arguments: [],
    options: []
}

