import { Box, Button, Flex, Heading, Tab, TabList, TabPanel, TabPanels, Tabs } from "@chakra-ui/react";
import Head from "next/head";
import Script from 'next/script';
import Fetch from "../components/api/Fetch";
import { FormArray, FormFetch } from "../components/Context/FormFetch";
import { FormField, FormPrimaryButton } from "../components/UI/Forms/Form";
import Icon from "../components/UI/Icon";
import FormFields from "./components/FormFields";

import { IoLogoLaravel, IoLogoReact, IoCodeDownloadOutline } from 'react-icons/io5'
import GettingStarted from "./components/GettingStarted";
import FormModels from "./components/FormModels";


export default function Home() {


  return (
    <div>
      <Head>
        <title>Form builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="https://tailwind-elements.com/js/index.min.js"></Script>

      <main className="px-10 py-8">
        <div className="bg-white p-4 rounded-lg">

          <Heading>Laravel React Form builder</Heading>

          <Tabs className="mt-6" defaultIndex={1}>
            <TabList>
              <Tab>Start Project</Tab>
              <Tab><Flex justifyContent='center' justifyItems='center' gap={1}><div><IoLogoLaravel className='w-full h-full' /></div> <div>Laravel</div></Flex></Tab>
              <Tab><Flex justifyContent='center' justifyItems='center' gap={1}><div><IoLogoReact className='w-full h-full' /></div> <div>React</div></Flex></Tab>
            </TabList>

            <TabPanels>

              <TabPanel>
                <GettingStarted />
              </TabPanel>
              <TabPanel>
                <Fetch endpoint="/api/laravel">
                  {(data) => {
                    return (
                      <FormFetch action="/api/laravel" data={data}>
                        {(form) => <FormModels form={form} models={data.models} />}
                      </FormFetch>
                    )
                  }}
                </Fetch>
              </TabPanel>

              <TabPanel>
                React
              </TabPanel>
            </TabPanels>
          </Tabs>

        </div>
      </main>
    </div>
  );
}

